version: '3.3'
services:
    app:
        build: ./app
        environment:
            - JAVA_OPTS=-Xms1024M -Xmx1024M
        ports:
            - 8080:8080
        depends_on:
            - db
        volumes:
            - app_logs:/usr/local/tomcat/logs
        command: >
            /bin/bash -c "
            sleep 10;
            catalina.sh run;
            "

    db:
        image: mysql:5.7.23
        restart: always
        volumes:
            - db_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=gestaotfc
            - MYSQL_USER=gestaotfc
            - MYSQL_PASSWORD=tfc
        ports:
            - 3306:3306
volumes:
    app_logs:
    db_data:

